name: kakii

on:
  issue_comment:
    types: [created, edited]

jobs:
  process-pr-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }} # Ensure it’s a comment on a PR
    steps:
      - name: Echo Comment Body
        env:
          COMMENTBODY: ${{ github.event.comment.body }}
        run: |
          echo "$COMMENTBODY"
