name: Check PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Process Comment and Set Environment Variables
        env:
          COMMENTBODY: ${{ github.event.comment.body }}
        run: |
          echo "$COMMENTBODY"
