name: Check PR Title or Process Comments

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  issue_comment:
    types: [created, edited]

jobs:
  check-pr-or-comment:
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    steps:
      - name: Process Pull Request or Comment
        env:
          COMMENTBODY: ${{ github.event.comment.body }}
        run: |
          echo "$COMMENTBODY"
